---
- name: Пример плейбука для подключения к серверу
  hosts: web
  become: yes

  tasks:
    - name: Вывод информации о сервере
      debug:
        msg: "Hello from server with IP 93.183.73.116"

    # Добавьте здесь другие задачи, которые вы хотите выполнить на сервере


