- name: Install nginx for Ubuntu
  apt:
    name: nginx
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: Install nginx for Oracle Linux
  yum:
    name: nginx
    state: latest
  when: ansible_distribution == 'OracleLinux'

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: yes
